name: ALIA
channels:
- pytorch
- defaults
dependencies:
- python
- pytorch-cuda
- pip
- torchvision
- pandas
- numpy
- seaborn
- pip:
    - numpy
    - clip
    - matplotlib
    - regex
    - wilds
    - omegaconf
    - wandb
    - scikit-image
    - torch
    - torchfile
    - torchtext
    - torchvision
    - tqdm
    - transformers
    - attrdict
    - wandb
    - diffusers[torch]
    - tyro
    - git+https://github.com/ildoonet/cutmix
    - git+https://github.com/openai/CLIP.git
    - cleanlab