name: ALIA
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - pandas
  - scipy
  - seaborn
  - torchvision
  - pytorch
  - cudatoolkit=11.7
  - pip
  - pip:
    - torchtext
    - omegaconf
    - wilds
    - wandb
    - scikit-image
    - tqdm
    - transformers
    - diffusers[torch]
    - tyro
    # - git+https://github.com/ildoonet/cutmix
    - git+https://github.com/openai/CLIP.git
    - fschat
