base_config: configs/Planes/base.yaml # config to inheit params from (should be dataset specific)
name: PlaneExtra # name of dataset

epochs: 100
model: resnet18

data: 
  base_dataset: PlanesExtra
  extra_dataset: PlanesExtra
  extraset_root: /shared/lisabdunlap/vl-attention
  extra_classes: ['airbus', 'boeing']

hps:
  lr: 0.001