base_config: configs/Planes/base.yaml # config to inheit params from (should be dataset specific)
name: Planes-Img2Img 

epochs: 100
model: resnet18

data: 
  base_dataset: Planes
  extra_dataset: Img2ImgDataset
  extra_root: 
  - /shared/lisabdunlap/edited/img2img/Planes/Colorfully_designed_{}_airplane_parked_on_the_runway,_grass_and_trees_in_the_backdrop/strength-0.6_guidance-7.5
  - /shared/lisabdunlap/edited/img2img/Planes/a_photo_of_a_{}_airplane_on_the_airport_tarmac,_surrounded_by_buildings_and_other_infrastructure/strength-0.6_guidance-5.0
  - /shared/lisabdunlap/edited/img2img/Planes/a_photo_of_a_{}_airplane_in_mid-flight,_landing_gear_deployed_against_a_clear_sky/strength-0.6_guidance-5.0
  - /shared/lisabdunlap/edited/img2img/Planes/a_photo_of_a_{}_airplane_parked_on_a_runway,_with_a_vast_desert_expanding_in_the_background/strength-0.6_guidance-5.0
  - /shared/lisabdunlap/edited/img2img/Planes/a_photo_of_a_{}_airplane_with_red_and_white_colors,_landing_gear_down,_against_a_backdrop_of_a_bustling_cityscape/strength-0.6_guidance-5.0
  extra_classes: ['airbus', 'boeing']
  
hps:
  lr: 0.001

filter:
  model: ViT-L/14 # CLIP model
  prompt: "a photo of an Airbus or Boeing airplane"
  negative_prompts: ["a photo of an object", "a photo of geometric shapes", "a photo", "an image", "a painting", "a cartoon of an airplane", "artwork of an airplane", "a black iamge"]
  load: True # set this to true after you comput the embeddings once 
  per_img: True # set this to true if you are doing an img2img method
  checkpoint_name: 'ckpt-Planes-none-filtered-resnet18-2.pth'