base_config: configs/Planes/base.yaml # config to inheit params from (should be dataset specific)
proj: DiffusionAugmentation-Planes # wandb project
name: Planes-Txt2img # name of dataset

epochs: 100
model: resnet18

data: 
  base_dataset: Planes
  extra_dataset: BasicDataset
  extra_root: /shared/lisabdunlap/edited/txt2img/Planes/A_photo_of_a_{}_airplane
  extra_classes: ['airbus', 'boeing']

hps:
  lr: 0.001

filter:
  model: ViT-L/14 # CLIP model
  prompt: "a photo of an airplane"
  negative_prompts: ["a photo of an object", "a photo of geometric shapes", "a photo", "an image", "a painting", "a cartoon of an airplane", "artwork of an airplane"]
  load: True # set this to true after you comput the embeddings once 
  per_img: False # set this to true if you are doing an img2img method
  checkpoint_name: 'ckpt-Planes-none-filtered-resnet18-0.pth'
  filtered_path: /shared/lisabdunlap/dataset_understanding/filtering_results/Planes-Txt2img/filtered_idxs/semantic_kept.npy